# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8299ce6c9ba4f2ca9bf01fb1dc4ef6051c5c5cbfbe4da7a9004c027b18e29e2f191c77629cdd81940ad3ea37d6eddd1d8779f4b9bb12ea39b9a49871ff57d832

test:
  secret_key_base: 48f30b773927d704c2b70562a8cd3f5ec7f2bd802674ec2b778b10875d6be825b6702f3cc9f93c732d9cedcee4fbd9b55d8f82ce61d7ac8e3e01bb28a51d3433

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
